server:
   port: 8090

spring:
  datasource:
    url: jdbc:jtds:sqlserver://192.168.1.3;DatabaseName=wangxiao2_sys
    username: sa
    password: sad!##DSEDw323343
    # 使用druid数据源
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    hikari: 
      connection-test-query: SELECT 1
    platform: sqlserver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 30000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    validation-query-timeout: 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 
    

mybatis:
  mapper-locations:
  - classpath:mapping/*.xml
  type-aliases-package: com.wangxiao.model 
 